/*
 * Clash of Clans API
 *
 * Check out <a href=\"https://developer.clashofclans.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash of Clans API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashofclans.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\". 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CocApi.Rest.Models;
using CocApi.Rest.Client;
using System.Reflection;

namespace CocApi.Rest.Test.Model
{
    /// <summary>
    ///  Class for testing ClanWar
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClanWarTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClanWar
        //private ClanWar instance;

        public ClanWarTests()
        {
            // TODO uncomment below to create an instance of ClanWar
            //instance = new ClanWar();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClanWar
        /// </summary>
        [Fact]
        public void ClanWarInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClanWar
            //Assert.IsType<ClanWar>(instance);
        }

        /// <summary>
        /// Test the property 'AttacksPerMember'
        /// </summary>
        [Fact]
        public void AttacksPerMemberTest()
        {
            // TODO unit test for the property 'AttacksPerMember'
        }

        /// <summary>
        /// Test the property 'Clan'
        /// </summary>
        [Fact]
        public void ClanTest()
        {
            // TODO unit test for the property 'Clan'
        }

        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Fact]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }

        /// <summary>
        /// Test the property 'Opponent'
        /// </summary>
        [Fact]
        public void OpponentTest()
        {
            // TODO unit test for the property 'Opponent'
        }

        /// <summary>
        /// Test the property 'PreparationStartTime'
        /// </summary>
        [Fact]
        public void PreparationStartTimeTest()
        {
            // TODO unit test for the property 'PreparationStartTime'
        }

        /// <summary>
        /// Test the property 'ServerExpiration'
        /// </summary>
        [Fact]
        public void ServerExpirationTest()
        {
            // TODO unit test for the property 'ServerExpiration'
        }

        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Fact]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }

        /// <summary>
        /// Test the property 'TeamSize'
        /// </summary>
        [Fact]
        public void TeamSizeTest()
        {
            // TODO unit test for the property 'TeamSize'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'WarTag'
        /// </summary>
        [Fact]
        public void WarTagTest()
        {
            // TODO unit test for the property 'WarTag'
        }
    }
}
