/*
 * Clash of Clans API
 *
 * Check out <a href=\"https://developer.clashofclans.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash of Clans API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashofclans.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\". 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CocApi.Rest.Models;
using CocApi.Rest.Client;
using System.Reflection;

namespace CocApi.Rest.Test.Model
{
    /// <summary>
    ///  Class for testing ClanCapitalRaidSeasonDistrict
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClanCapitalRaidSeasonDistrictTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClanCapitalRaidSeasonDistrict
        //private ClanCapitalRaidSeasonDistrict instance;

        public ClanCapitalRaidSeasonDistrictTests()
        {
            // TODO uncomment below to create an instance of ClanCapitalRaidSeasonDistrict
            //instance = new ClanCapitalRaidSeasonDistrict();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClanCapitalRaidSeasonDistrict
        /// </summary>
        [Fact]
        public void ClanCapitalRaidSeasonDistrictInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClanCapitalRaidSeasonDistrict
            //Assert.IsType<ClanCapitalRaidSeasonDistrict>(instance);
        }

        /// <summary>
        /// Test the property 'AttackCount'
        /// </summary>
        [Fact]
        public void AttackCountTest()
        {
            // TODO unit test for the property 'AttackCount'
        }

        /// <summary>
        /// Test the property 'DestructionPercent'
        /// </summary>
        [Fact]
        public void DestructionPercentTest()
        {
            // TODO unit test for the property 'DestructionPercent'
        }

        /// <summary>
        /// Test the property 'DistrictHallLevel'
        /// </summary>
        [Fact]
        public void DistrictHallLevelTest()
        {
            // TODO unit test for the property 'DistrictHallLevel'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Stars'
        /// </summary>
        [Fact]
        public void StarsTest()
        {
            // TODO unit test for the property 'Stars'
        }

        /// <summary>
        /// Test the property 'TotalLooted'
        /// </summary>
        [Fact]
        public void TotalLootedTest()
        {
            // TODO unit test for the property 'TotalLooted'
        }

        /// <summary>
        /// Test the property 'Attacks'
        /// </summary>
        [Fact]
        public void AttacksTest()
        {
            // TODO unit test for the property 'Attacks'
        }
    }
}
