/*
 * Clash of Clans API
 *
 * Check out <a href=\"https://developer.clashofclans.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash of Clans API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashofclans.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\". 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CocApi.Rest.Models;
using CocApi.Rest.Client;
using System.Reflection;

namespace CocApi.Rest.Test.Model
{
    /// <summary>
    ///  Class for testing Key
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KeyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Key
        //private Key instance;

        public KeyTests()
        {
            // TODO uncomment below to create an instance of Key
            //instance = new Key();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Key
        /// </summary>
        [Fact]
        public void KeyInstanceTest()
        {
            // TODO uncomment below to test "IsType" Key
            //Assert.IsType<Key>(instance);
        }


        /// <summary>
        /// Test the property 'CidrRanges'
        /// </summary>
        [Fact]
        public void CidrRangesTest()
        {
            // TODO unit test for the property 'CidrRanges'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'DeveloperId'
        /// </summary>
        [Fact]
        public void DeveloperIdTest()
        {
            // TODO unit test for the property 'DeveloperId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'VarKey'
        /// </summary>
        [Fact]
        public void VarKeyTest()
        {
            // TODO unit test for the property 'VarKey'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Scopes'
        /// </summary>
        [Fact]
        public void ScopesTest()
        {
            // TODO unit test for the property 'Scopes'
        }
        /// <summary>
        /// Test the property 'Tier'
        /// </summary>
        [Fact]
        public void TierTest()
        {
            // TODO unit test for the property 'Tier'
        }
        /// <summary>
        /// Test the property 'Origins'
        /// </summary>
        [Fact]
        public void OriginsTest()
        {
            // TODO unit test for the property 'Origins'
        }
        /// <summary>
        /// Test the property 'ValidUntil'
        /// </summary>
        [Fact]
        public void ValidUntilTest()
        {
            // TODO unit test for the property 'ValidUntil'
        }

    }

}
