/*
 * Clash of Clans API
 *
 * Check out <a href=\"https://developer.clashofclans.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash of Clans API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashofclans.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\". 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CocApi.Rest.Models;
using CocApi.Rest.Client;
using System.Reflection;

namespace CocApi.Rest.Test.Model
{
    /// <summary>
    ///  Class for testing Player
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlayerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Player
        //private Player instance;

        public PlayerTests()
        {
            // TODO uncomment below to create an instance of Player
            //instance = new Player();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Player
        /// </summary>
        [Fact]
        public void PlayerInstanceTest()
        {
            // TODO uncomment below to test "IsType" Player
            //Assert.IsType<Player>(instance);
        }


        /// <summary>
        /// Test the property 'Achievements'
        /// </summary>
        [Fact]
        public void AchievementsTest()
        {
            // TODO unit test for the property 'Achievements'
        }
        /// <summary>
        /// Test the property 'AttackWins'
        /// </summary>
        [Fact]
        public void AttackWinsTest()
        {
            // TODO unit test for the property 'AttackWins'
        }
        /// <summary>
        /// Test the property 'BestTrophies'
        /// </summary>
        [Fact]
        public void BestTrophiesTest()
        {
            // TODO unit test for the property 'BestTrophies'
        }
        /// <summary>
        /// Test the property 'BestVersusTrophies'
        /// </summary>
        [Fact]
        public void BestVersusTrophiesTest()
        {
            // TODO unit test for the property 'BestVersusTrophies'
        }
        /// <summary>
        /// Test the property 'BuilderBaseTrophies'
        /// </summary>
        [Fact]
        public void BuilderBaseTrophiesTest()
        {
            // TODO unit test for the property 'BuilderBaseTrophies'
        }
        /// <summary>
        /// Test the property 'BuilderHallLevel'
        /// </summary>
        [Fact]
        public void BuilderHallLevelTest()
        {
            // TODO unit test for the property 'BuilderHallLevel'
        }
        /// <summary>
        /// Test the property 'ClanCapitalContributions'
        /// </summary>
        [Fact]
        public void ClanCapitalContributionsTest()
        {
            // TODO unit test for the property 'ClanCapitalContributions'
        }
        /// <summary>
        /// Test the property 'DefenseWins'
        /// </summary>
        [Fact]
        public void DefenseWinsTest()
        {
            // TODO unit test for the property 'DefenseWins'
        }
        /// <summary>
        /// Test the property 'Donations'
        /// </summary>
        [Fact]
        public void DonationsTest()
        {
            // TODO unit test for the property 'Donations'
        }
        /// <summary>
        /// Test the property 'DonationsReceived'
        /// </summary>
        [Fact]
        public void DonationsReceivedTest()
        {
            // TODO unit test for the property 'DonationsReceived'
        }
        /// <summary>
        /// Test the property 'ExpLevel'
        /// </summary>
        [Fact]
        public void ExpLevelTest()
        {
            // TODO unit test for the property 'ExpLevel'
        }
        /// <summary>
        /// Test the property 'Heroes'
        /// </summary>
        [Fact]
        public void HeroesTest()
        {
            // TODO unit test for the property 'Heroes'
        }
        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Fact]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Spells'
        /// </summary>
        [Fact]
        public void SpellsTest()
        {
            // TODO unit test for the property 'Spells'
        }
        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Fact]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }
        /// <summary>
        /// Test the property 'TownHallLevel'
        /// </summary>
        [Fact]
        public void TownHallLevelTest()
        {
            // TODO unit test for the property 'TownHallLevel'
        }
        /// <summary>
        /// Test the property 'Troops'
        /// </summary>
        [Fact]
        public void TroopsTest()
        {
            // TODO unit test for the property 'Troops'
        }
        /// <summary>
        /// Test the property 'Trophies'
        /// </summary>
        [Fact]
        public void TrophiesTest()
        {
            // TODO unit test for the property 'Trophies'
        }
        /// <summary>
        /// Test the property 'VersusBattleWinCount'
        /// </summary>
        [Fact]
        public void VersusBattleWinCountTest()
        {
            // TODO unit test for the property 'VersusBattleWinCount'
        }
        /// <summary>
        /// Test the property 'VersusBattleWins'
        /// </summary>
        [Fact]
        public void VersusBattleWinsTest()
        {
            // TODO unit test for the property 'VersusBattleWins'
        }
        /// <summary>
        /// Test the property 'WarStars'
        /// </summary>
        [Fact]
        public void WarStarsTest()
        {
            // TODO unit test for the property 'WarStars'
        }
        /// <summary>
        /// Test the property 'BuilderBaseLeague'
        /// </summary>
        [Fact]
        public void BuilderBaseLeagueTest()
        {
            // TODO unit test for the property 'BuilderBaseLeague'
        }
        /// <summary>
        /// Test the property 'Clan'
        /// </summary>
        [Fact]
        public void ClanTest()
        {
            // TODO unit test for the property 'Clan'
        }
        /// <summary>
        /// Test the property 'League'
        /// </summary>
        [Fact]
        public void LeagueTest()
        {
            // TODO unit test for the property 'League'
        }
        /// <summary>
        /// Test the property 'LegendStatistics'
        /// </summary>
        [Fact]
        public void LegendStatisticsTest()
        {
            // TODO unit test for the property 'LegendStatistics'
        }
        /// <summary>
        /// Test the property 'PlayerHouse'
        /// </summary>
        [Fact]
        public void PlayerHouseTest()
        {
            // TODO unit test for the property 'PlayerHouse'
        }
        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'TownHallWeaponLevel'
        /// </summary>
        [Fact]
        public void TownHallWeaponLevelTest()
        {
            // TODO unit test for the property 'TownHallWeaponLevel'
        }
        /// <summary>
        /// Test the property 'WarPreference'
        /// </summary>
        [Fact]
        public void WarPreferenceTest()
        {
            // TODO unit test for the property 'WarPreference'
        }

    }

}
