/*
 * Clash of Clans API
 *
 * Check out <a href=\"https://developer.clashofclans.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash of Clans API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashofclans.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\". 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CocApi.Rest.Models;
using CocApi.Rest.Client;
using System.Reflection;

namespace CocApi.Rest.Test.Model
{
    /// <summary>
    ///  Class for testing PlayerLegendStatistics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlayerLegendStatisticsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PlayerLegendStatistics
        //private PlayerLegendStatistics instance;

        public PlayerLegendStatisticsTests()
        {
            // TODO uncomment below to create an instance of PlayerLegendStatistics
            //instance = new PlayerLegendStatistics();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PlayerLegendStatistics
        /// </summary>
        [Fact]
        public void PlayerLegendStatisticsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PlayerLegendStatistics
            //Assert.IsType<PlayerLegendStatistics>(instance);
        }


        /// <summary>
        /// Test the property 'CurrentSeason'
        /// </summary>
        [Fact]
        public void CurrentSeasonTest()
        {
            // TODO unit test for the property 'CurrentSeason'
        }
        /// <summary>
        /// Test the property 'LegendTrophies'
        /// </summary>
        [Fact]
        public void LegendTrophiesTest()
        {
            // TODO unit test for the property 'LegendTrophies'
        }
        /// <summary>
        /// Test the property 'BestBuilderBaseSeason'
        /// </summary>
        [Fact]
        public void BestBuilderBaseSeasonTest()
        {
            // TODO unit test for the property 'BestBuilderBaseSeason'
        }
        /// <summary>
        /// Test the property 'BestSeason'
        /// </summary>
        [Fact]
        public void BestSeasonTest()
        {
            // TODO unit test for the property 'BestSeason'
        }
        /// <summary>
        /// Test the property 'PreviousBuilderBaseSeason'
        /// </summary>
        [Fact]
        public void PreviousBuilderBaseSeasonTest()
        {
            // TODO unit test for the property 'PreviousBuilderBaseSeason'
        }
        /// <summary>
        /// Test the property 'PreviousSeason'
        /// </summary>
        [Fact]
        public void PreviousSeasonTest()
        {
            // TODO unit test for the property 'PreviousSeason'
        }

    }

}
