// this file was initially auto generated
// it will not be overwritten

/*
 * Clash of Clans API
 *
 * Check out <a href=\"https://developer.clashofclans.com/#/getting-started\" target=\"_parent\">Getting Started</a> for instructions and links to other resources. Clash of Clans API uses <a href=\"https://jwt.io/\" target=\"_blank\">JSON Web Tokens</a> for authorizing the requests. Tokens are created by developers on <a href=\"https://developer.clashofclans.com/#/account\" target=\"_parent\">My Account</a> page and must be passed in every API request in Authorization HTTP header using Bearer authentication scheme. Correct Authorization header looks like this: \"Authorization: Bearer API_TOKEN\". 
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using CocApi.Rest.Client;
using CocApi.Rest.Models;

namespace CocApi.Rest.Apis
{
    /// <summary>
    /// Validate requests and process server responses
    /// </summary>
    public class ClansApi : BaseApis.ClansApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClansApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ClansApi(ILogger<ClansApi> logger, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider,
            TokenProvider<ApiKeyToken> apiKeyProvider
        )
        : base(logger, httpClient, jsonSerializerOptionsProvider,
            apiKeyProvider)
        {
        }

        protected override void OnErrorFetchClan(Exception exception, string clanTag, string pathFormat, string path)
        {
            Logger.LogError(exception, "There was an error fetching the clan for clanTag: {clanTag}", clanTag);
        }

        protected override void OnErrorFetchClanMembers(Exception exception, string pathFormat, string path, string clanTag, int? limit, string? after, string? before)
        {
            Logger.LogError(exception, "There was an error fetching the clan members for clanTag: {clanTag}", clanTag);
        }

        protected override void OnErrorFetchClanWarLeagueGroup(Exception exception, string pathFormat, string path, string clanTag, bool? realtime)
        {
            Logger.LogError(exception, "There was an error fetching the clan war league group for clanTag: {clanTag}", clanTag);
        }

        protected override void OnErrorFetchClanWarLeagueWar(Exception exception, string pathFormat, string path, string warTag, bool? realtime)
        {
            Logger.LogError(exception, "There was an error fetching the clan war league war for warTag: {warTag}", warTag);
        }

        protected override void OnErrorFetchClanWarLog(Exception exception, string pathFormat, string path, string clanTag, int? limit, string? after, string? before)
        {
            Logger.LogError(exception, "There was an error fetching the clan war log for clanTag: {clanTag}", clanTag);
        }

        protected override void OnErrorFetchCurrentWar(Exception exception, string pathFormat, string path, string clanTag, bool? realtime)
        {
            Logger.LogError(exception, "There was an error fetching the current war for clanTag: {clanTag}", clanTag);
        }
    }
}


